DATA_FOLDER = 'data_sources'
RAW_DATA_FILE = 'data_sources\mall_customers_raw.csv'
PROCESSED_DATA_FILE = 'data_sources\mall_customers_processed.csv'
MODEL_OUTPUT = 'saved_entities\models'
PARAMETERS_OUTPUT = 'saved_entities\parameters'